export enum Configuration {
  PORT = "PORT",
  DB_HOST = "DB_HOST",
  DB_PORT = "DB_PORT",
  DB_USER = "DB_USER",
  DB_PASS = "DB_PASS",
  DB_NAME = "DB_NAME",
  JWT_SECRET = "JWT_SECRET",
  JWT_EXPIRATION_TIME = "JWT_EXPIRATION_TIME",
}
